---

# - name: Import Docker APT public key.
#   apt_key:
#     keyserver: "{{ docker_pubkey_server }}"
#     id: "{{ docker_pubkey_id }}"
#     state: present
#   when: ansible_os_family == 'Debian'

# - name: Install yum-utils if necessary.
#   yum:
#     name: yum-utils
#     state: present
#   when: ansible_os_family == 'RedHat'

# - name: Install apt-transport-https if necessary.
#   apt:
#     name: apt-transport-https
#     state: present
#   when: ansible_os_family == 'Debian'

# - name: Debug
#   debug:
#     msg: "Values are: {{ docker_yum_repo }} and {{ docker_yum_gpgkey }}"

- name: Install Docker dependencies.
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies }}"

- name: Delete docker-ce
  ignore_errors: yes
  yum:
    name: docker-ce
    state: absent
  tags:
    - docker-update

- name: Downloading docker
  get_url:
    url: https://download.docker.com/linux/centos/7/x86_64/edge/Packages/docker-ce-17.07.0.ce-1.el7.centos.x86_64.rpm
    # url: https://download.docker.com/linux/centos/7/x86_64/edge/Packages/docker-ce-17.11.0.ce-1.el7.centos.x86_64.rpm
    dest: /tmp/docker-ce-installation.rpm
  tags:
    - docker-update
    
- name: Install the Docker Engine from file.
  yum:
    name: /tmp/docker-ce-installation.rpm
    state: present
  tags:
    - docker-update

- name: Delete docker RPM
  file:
    path: /tmp/docker-ce-installation.rpm
    state: absent
  tags:
    - docker-update

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: restarted
    enabled: yes
  tags:
    - docker-update

