---
- hosts: all
  become: true

  vars:
    platform_version: "1.4.0-SANDBOX"
    docker_local_users: true
    docker_ldap_users: true
    docker_local_users_list: ['adop', 'docker']
    docker_ldap_users_list: ['ishakitko', 'okoggu', 'mkaminski01', 'akrivas', 'stanniru', 'hsareddy', 'predabothu', 'rgella', 'snandigam', 'syerabolu']
    docker_storage_dir: /u01/appl/docker
    adop_ldap_domain: liberty.adop.local
    restheart_ldap_email_domains: "{{ adop_ldap_domain }},accenture.com,libertyglobal.com"
    public_domain: sandbox-devops.upc.biz

    frontent_1_private_ip: 172.31.124.19
    internal_platform_ip_or_lb: "{{ public_domain }}"
    logstash_host: "{{ internal_platform_ip_or_lb }}"
    proxy_host: 172.31.133.12
    # 172.31.133.12
    # 8080
    proxy_port: 8080
    proxy_url: "http://{{ proxy_host }}:{{ proxy_port }}"
    no_proxy_array: [ '{{ public_domain }}', '127.0.0.1',
    '172.28.47.12', 'amsxodape6-scan.ux.upc.biz', '10.64.98.190', '10.64.98.191',
    '10.*.*.*', 'localhost', "registry-{{ public_domain }}", "selenium-{{ public_domain }}", 'kibana', 'gerrit', 'jenkins', 'elasticsearch', 'logstash', 'kibana', 'proxy', 'ldap', 'gerrit-mysql', 'gerrit', 'sensu-uchiwa',
    'sensu-api', 'sensu-server', 'sensu-client-services', 'sensu-client-system', 'sensu-rabbitmq',
    'sensu-redis', 'sonar-mysql', 'sonar', 'jenkins', 'selenium-hub', 'selenium-node-chrome', 'selenium-node-firefox',
    'ldap-ltb', 'ldap-phpadmin', 'registry', 'nexus', '*slave*',
    'gitlab', 'restheart', 'mongodb', '.cioio.net', '.liberty.biz', '.upc.biz', '.virginmedia.com', '.lgi.io']
    no_proxy_hosts: "{{ no_proxy_array | join(',') }}"
    no_proxy_hosts_pattern: "{{ no_proxy_array | join('\\|') }}"
    no_proxy_hosts_join_pipe: "{{ no_proxy_array | join('|') }}"
    adop_repo_url: https://github.com/svscorp/adop-docker-compose.git
    adop_repo_revision: HEAD
    adop_protocol: https
    adop_nginx_port: 443
    adop_nginx_ssl: "on"
    adop_redirect_protocol: https
    platform_name: lgadop

  environment:
    TARGET_HOST: "{{ public_domain }}" #"{{ ansible_eno16780032.ipv4.address }}"
    CUSTOM_NETWORK_NAME: bridge
    PROXY_IP: "{{ public_domain }}"
    # LOGSTASH_HOST: "{{ public_domain }}" #"{{ ansible_eno16780032.ipv4.address }}"
    LOGSTASH_HOST: "{{ internal_platform_ip_or_lb }}"
    HTTP_PROXY_HOST: "{{ proxy_host }}"
    HTTP_PROXY_PORT: "{{ proxy_port }}"
    HTTPS_PROXY_HOST: "{{ proxy_host }}"
    HTTPS_PROXY_PORT: "{{ proxy_host }}"
    HTTP_NON_PROXY_HOSTS: "{{ no_proxy_hosts_pattern }}"
    HTTP_NON_PROXY_HOSTS_JOIN_PIPE: "{{ no_proxy_hosts_join_pipe }}"
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
    no_proxy: "{{ no_proxy_hosts }}"
    PLATFORM_NAME: "{{ platform_name }}"
    INTERNAL_TARGET_HOST: "{{ internal_platform_ip_or_lb }}"
    HTTP_PROXY: "{{ proxy_url }}"
    HTTPS_PROXY: "{{ proxy_url }}"
    NO_PROXY: "{{ no_proxy_hosts }}"
    FRONTEND_1_PRIVATE_IP: "{{ frontent_1_private_ip }}"

  roles:
    # - { role: adop-destroy-quickstart-role }
    # - { role: geerlingguy.repo-epel }
    - { role: adop-quickstart-role }