- name: Debugging variables
  debug:
    msg: "Platform Name is: {{ platform_name }} "

- name: Installing basic packages
  include: basic.yml
  tags:
    - basic

- name: Install and configure pip
  include: pip.yml
  tags:
    - pip

- name: Install and configure adop
  include: adop.yml
  tags:
    - adop
  # when: "docker_info.stdout.find('Swarm: active') == -1 and inventory_hostname == groups['docker_swarm_manager'][0]"
  # commented out for initial setup (nodes are always active). For "live" running phase use the above and put odes to maintenance mode
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Post addop LGI tweaks
  include: post-adop.yml
  tags:
    - post-adop
