proxy:
  volumes:
    - nginx_config:/etc/nginx
    - nginx_releasenote:/usr/share/nginx/html
    - nginx_ssl:/etc/nginx/ssl

ldap:
  volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap

gerrit-mysql:
  volumes:
    - gerrit_mysql_data:/var/lib/mysql

gerrit:
  user: root
  volumes:
    - git_repos:/var/git/repos 
    - gerrit_review_site:/var/gerrit/review_site 

sensu-api:
  volumes:
    - sensu_api_conf:/etc/sensu/conf.d
    - sensu_server_check:/etc/sensu/check.d

sensu-server:
  volumes:
    - sensu_server_conf:/etc/sensu/conf.d
    - sensu_server_check:/etc/sensu/check.d

sensu-client:
  volumes:
    - sensu_client_conf:/etc/sensu/conf.d

sensu-rabbitmq:
  volumes:
    - sensu_rabbitmq_data:/var/lib/rabbitmq

sensu-redis:
  volumes:
    - sensu_redis_data:/data

sonar-mysql:
  volumes:
    - sonar_mysql_data:/var/lib/mysql 

sonar:
  volumes:
    - sonar_data:/opt/sonarqube/data
    - sonar_conf:/opt/sonarqube/conf
    - sonar_extensions:/opt/sonarqube/extensions 
    - sonar_logs:/opt/sonarqube/logs

jenkins:
  user: root 
  volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

nexus:
  volumes:
    - nexus_sonatype_work:/sonatype-work

registry:
  volumes:
    - registry_certs:/certs
    - registry_data:/data

### EXTRA TOOLS ###

gitlab:
  volumes:
    - gitlab_config:/etc/gitlab
    - gitlab_data:/var/opt/gitlab

restheart:
  volumes:
    - restheart_config:/opt/restheart/etc:ro

mongodb:
  volumes:
    - mongodb_data:/data/db

### JENKINS SLAVES ###

jenkins-slave-shared-1:
  volumes:
    - jenkins_slave_shared_1_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-shared-2:
  volumes:
    - jenkins_slave_2_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-shared-3:
  volumes:
    - jenkins_slave_3_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-bss-clarify:
  volumes:
    - jenkins_slave_bss_clarify_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-bss-kenan:
  volumes:
    - jenkins_slave_bss_kenan_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-oss-asap:
  volumes:
    - jenkins_slave_oss_asap_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-oss-cdm:
  volumes:
    - jenkins_slave_oss_cdm_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-online-aem-1:
  volumes:
    - jenkins_slave_online_aem_1_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-online-aem-2:
  volumes:
    - jenkins_slave_online_aem_2_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-mdw-core-off-1:
  volumes:
    - jenkins_slave_mdw_core_off_1_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-mdw-core-off-2:
  volumes:
    - jenkins_slave_mdw_core_off_2_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins-slave-obo:
  volumes:
    - jenkins_slave_obo_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock
